### ISSUE TITLE
Macro for upgradable contracts

### ISSUE THREAD

**Issue by roshaans** [NEARFoundation/near-contract-tools#11]
It would be very neat to have a standardized way of upgrading a smart contract and migrating its state to mitigate common security vulnerabilities. 

- Should provide a callback for calling a migration state
- Can only be executed with a full access key or by the contract owner. 
- Possibly support storing the previous state of the contract in case of an immediate rollback

**Comment by encody** [comment]
Depends on #16

**Comment by nearken** [comment]
Denys recommended checking out this SputnickDAO implementation of Upgradability: https://github.com/near-daos/sputnik-dao-contract/blob/main/README.md#upgradability

**Comment by encody** [comment]
#48

**Comment by encody** [comment]
@nearken Is the macro for upgradable contracts done?
