### ISSUE TITLE
Fuller examples

### ISSUE THREAD

**Issue by ryancwalsh** [NEARFoundation/near-contract-tools#18]
Let's add (in a separate repo if necessary... and this one can link to it) complete examples of projects taking advantage of near-contract-tools.

E.g. https://github.com/NEARFoundation/near-contract-tools/blob/01a64242717af71a27fa49197a96912d1c5aeedb/README.md#fungible-token isn't enough to get me started. Part (most?) of it is that I'm new to Rust, but I'm having trouble knowing where to put these lines, what Cargo.toml needs to contain, how to build the project, etc. So a full working example would be helpful.

I looked at https://github.com/NEAR-Edu/near-certification-tools/blob/938255e1adbecbe0605c2749f9a7ebd9a9df317a/data-contract/src/contract.rs#L5 but couldn't figure it out. (Maybe certain types of macros are different from "derive" macros?

**Comment by encody** [comment]
near-certification-tools is using [near-contract-tools v0.2.0](https://github.com/NEAR-Edu/near-certification-tools/blob/938255e1adbecbe0605c2749f9a7ebd9a9df317a/data-contract/Cargo.toml#L10)

[The code in the README](/README.md#fungible-token) goes anywhere in a Rust project built to WASM (a smart contract). Cargo.toml just needs to contain `near-contract-tools` as a dependency.

**Comment by ryancwalsh** [comment]
@encody Yeah I tried this but couldn't figure it out. I.e. I (temporarily, for the sake of testing/exploration) added this to my donation_matcher_contract project:

```
use near_contract_tools::FungibleToken;
use near_sdk::near_bindgen;

#[derive(FungibleToken)]
#[fungible_token(
    name = "My Fungible Token",
    symbol = "MYFT",
    decimals = 18,
    no_hooks
)]
#[near_bindgen]
struct FungibleToken {
    // ...
}
```

I wasn't sure what to put in place of the ellipsis. 

And even when compiling to Wasm, I couldn't get tests to then read it.

So that's why I was thinking maybe we need more documentation here.

I can keep trying today.

**Comment by encody** [comment]
@ryancwalsh You don't need to put anything in the struct if you don't want to. The macro handles its own state separately from the default struct / `STATE` key. It is perfectly valid for it to be empty.
