### ISSUE TITLE
Extract error strings to constants

### ISSUE THREAD

**Issue by encody** [NEARFoundation/near-contract-tools#22]
For example, `"Unauthorized"` in https://github.com/NEARFoundation/near-contract-tools/blob/main/src/rbac.rs#L43 could be extracted to a constant called something like `REQUIRE_ROLE_FAIL_MESSAGE` or something like that.

Alternatively, change the function signature (or add new functions) that accept a `fail_message` parameter to allow contract authors to customize the messages to their liking.

**Comment by nearken** [comment]
PR #37
