### ISSUE TITLE
Add unchecked versions of functions with no side-effects or permissioning

### ISSUE THREAD

**Issue by encody** [NEARFoundation/near-contract-tools#6]
~For example, `ownership::Ownership::propose_owner_internal` would not call `require_owner` or emit an `OwnershipEvent::Propose` event.~

For `Owner`, it might make more sense to just have a non-event-emitting version of `update_owner` and `update_proposed`. For `Pause`, `set_is_paused` already doesn’t emit events or have any `require!` calls, so it wouldn’t require updating for this issue. I think the method names could use some work though, i.e. just by looking at the name of the method I should be able to tell whether it emits events & performs, for example, predecessor checks, and also the method that does perform those things should appear to the untrained eye as the “natural” choice. Hence, I had initially thought using names like `update_owner_internal` would be a good idea, but maybe `update_owner_unchecked` would be a better choice.

**Comment by encody** [comment]
It should be noted that the unchecked versions of the methods in the `nep141` module are currently called `internal_*`, which would need to be changed in order for this issue to be completed.

**Comment by nearken** [comment]
https://github.com/NEARFoundation/near-contract-tools/pull/33

**Comment by encody** [comment]
Re: https://github.com/NEARFoundation/near-contract-tools/pull/33, might be worth implementing unit tests for the new unchecked functions, as well as reimplementing the non-unchecked functions in terms of the unchecked functions to reduce code duplication, if only slightly.

**Comment by nearken** [comment]
makes sense to me, will add work this in to next PR

**Comment by encody** [comment]
@nearken 

Something like this:
```rust
fn update_proposed(&mut self, new: Option<AccountId>) {
    let old = Self::slot_proposed_owner().read();
    if old != new {
        OwnerEvent::Propose {
            old,
            new: new.clone(),
        }
        .emit();
        self.update_proposed_unchecked(new);
    }
}
```

**Comment by encody** [comment]
Last thing would be renaming functions in other components. For example, the functions that we are now referring to as "unchecked" are called "internal" in [`nep141`](https://github.com/NEARFoundation/near-contract-tools/blob/main/src/standard/nep141.rs#L145).
