### ISSUE TITLE
Update workspaces version and clean up view invocations

### ISSUE THREAD

**Issue by nearken** [NEARFoundation/near-contract-tools#67]
Update workspaces version and clean up the tests in workspaces to follow best practices

**Comment by encody** [comment]
I've been hesitant to upgrade to workspaces-rs@0.5.0 because that version doesn't support Windows yet, and I do a significant portion of my development work on a Windows machine.

**Comment by nearken** [comment]
@encody ok that makes sense, I can hold off on updating version and work on cleaning up view invocations

**Comment by encody** [comment]
Closed by #81
