### ISSUE TITLE
Write security invariants for every component

### ISSUE THREAD

**Issue by encody** [NEARFoundation/near-contract-tools#74]
For assistance on the audit, every component should have a list of invariants / assumptions for use and for every function. For example, the Owner component's list would include:

* The root storage key is not used for any other data.
* Only the owner will ever be able to call `own_renounce_owner`, `own_propose_owner`.
* Only the account most recently proposed (by the current owner, via `own_propose_owner`) will be able to call `own_accept_owner`.
* After `own_accept_owner` has been called, the formerly "proposed owner" will become the owner, and the former owner will be removed. There will not be a "proposed owner".
* Et cetera.

This list should appear in the module level documentation comments for each component.

**Comment by twitu** [comment]
Taking a look at some of the components, I've observed that only few contracts expose external functions and even fewer have in-variants. For e.g.

* Owner - multiple invariants - docs added in #75 
* Rbac - no external functions - no visible invariants in default trait implementations
* Pause - one external function - no visible invariants in default trait implementations
* Migrate - one external function - User needs to provide migration implementation

Is the current audit only about documenting invariants for external functions?

**Comment by encody** [comment]
@twitu Good point. It should be about invariants for all functions, regardless of externality.
